server:
  port: 8101
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.86.124:3306/db_bi
    username: root
    password: XRGyR7ZcnksykxXK
  # Redis 配置
  redis:
    database: 1
    host: 117.72.86.124
    port: 6379
    timeout: 5000
    password: jx4bAsLCD83afPcX
  # Elasticsearch 配置
  elasticsearch:
    uris: http://117.72.86.124:9200
    username: root
    password: 123456
